### ISSUE TITLE
Review UML

### ISSUE THREAD

**Issue by NicolasGlassey** [NicolasGlassey/VIR1-Deliver#3]
@yannickcpnv 

Il m'a semblé plus simple de vous faire une review sur les diagrammes visuels. J'espère que cela sera clair pour vous. Sinon on se fait un petit meeting jeudi matin.

[VIR1_Deliver_Review_UML.pdf](https://github.com/yannickcpnv/VIR1-Deliver/files/8900292/VIR1_Deliver_Review_UML.pdf)

**Comment by Penfu** [comment]
@NicolasGlassey Merci pour le retour, on est discute jeudi.

Des issues distinctes on étaient créées d'après cette synthèse.
