### ISSUE TITLE
Appel unique, description globale

### ISSUE THREAD

**Issue by Penfu** [NicolasGlassey/VIR1-Deliver#4]
De @NicolasGlassey #3 

Il manque la notion de "loop". Autant l'appel de la méthode "describe" du VpcHelper sera unique lors de la séquence, autant il y a de fortes chances que nous ayons plusieurs subnets, plusieurs security groups...

Selon votre diagramme de classes, vos helpers n'acceptent que des valeurs uniques (string simple) et non pas des listes de string.

Que penseriez-vous du faites de pouvoir demander au "subnetHelper" de décrire une liste de subnets ? Déchargeant ainsi le DescribeInfra de ce travail.

**Comment by Penfu** [comment]
@NicolasGlassey Il n'y a simplement pas de loop. 

Comme indiqué dans le wiki, nous recevons le nom d'un Vpc en input et devons sortir un JSON de ses divers attributs et ceux des objets EC2 en relations (subnets, security Groupes, keypairs et instances). 

Nos méthodes "describe" se basent sur un Vpc, car c'est toujours dans le contexte d'un Vpc que nous souhaitons récupérer des informations.

## Méthode "describe" de subnetHelper

- **Brief** Fetches the Subnets of a given VPC from the AWS EC2 SDK
- **Param** vpcId: string
- **Returns** Promise<AWS.EC2.SubnetList>

De ce fait, subnetHelper décrit déjà une liste de subnets et n'en a aucunement la charge.

**Comment by NicolasGlassey** [comment]
@Penfu 

Du coup on reçoit bien une liste de subnets, c'est ce dont nous avions besoin.

Et si on continue le processus, ensuite vous allez devoir décrire les instances, par subnet. Comment construisez-vous, pour chaque subnet, sa liste d'instances ?

(oui on peut lister toutes les instances d'un vpc en une commande ;), mais le besoin est de connaître quelles instances est dans quel sous-réseau).

**Comment by NicolasGlassey** [comment]
@Penfu 

Les "sous-objets" sont simplement listés pour l'instant mais ne respectent pas la structure présenté ici:

https://docs.aws.amazon.com/fr_fr/vpc/latest/userguide/VPC_NAT_Instance.html

Ecrire une story pour les prochains dév.

**Comment by YannickBaudraz** [comment]
La [story](https://icescrum.cpnv.ch/p/VIR1DELIVE/#/backlog/sandbox/story/5433) a été créée sur IceScrum
