### ISSUE TITLE
Responsabilité de génération de la chaîne JSON

### ISSUE THREAD

**Issue by Penfu** [NicolasGlassey/VIR1-Deliver#5]
De @NicolasGlassey #3 

Les méthodes "describe" des différents helpers génèrent un objet (selon le diagramme de classes), alors que la méthode describe de "DescribeInfra" retourne un string.

Est-ce vraiment la responsabilité du DescribeInfra de faire ce travail de "deserialization" de l'objet json ?

**Comment by Penfu** [comment]
Après conception avec @yannickcpnv, il est de notre volonté de conserver les classes helpers génériques.
Et ceux afin de respecter une responsabilité unique. Seul la classe DescribeInfra a connaissance du format d'output demandé.

**Comment by NicolasGlassey** [comment]
@Penfu @yannickcpnv 

Je vous suis. Par contre en passent en paramètre l'objet que l'on veut obtenir, on sous-traite que le traitement (la serialisation, desarialization à Helper). Le format de sortie est du coup bien défini par l'appelant, mais c'est bien votre Helper qui livre directement le bon format.
