### ISSUE TITLE
Extraction des méthodes exists dans le Core

### ISSUE THREAD

**Issue by Penfu** [NicolasGlassey/VIR1-Deliver#6]
De @NicolasGlassey https://github.com/yannickcpnv/VIR1-Deliver/issues/3

Les méthodes "exists" vont pouvoir être "sorties" de vos helpers et vous pourrez ainsi utiliser le "AwsCloudClientImpl" pour réaliser vos vérifications. Regardez avec Mario. Je crois qu'il est prêt à vous livrer les méthodes exists dans son "core" package.

**Comment by Penfu** [comment]
@NicolasGlassey les méthodes "exists" ne sont jamais utilisées hors tests. Elles non pas vocation à être utilisées dans notre module.

@Thynkon a en effet fini de reprendre celles de nos divers objets EC2, nous pouvons maintenant en tout point les retirer de Deliver.

**Comment by NicolasGlassey** [comment]
Donc allez-vous utiliser le package de @Thynkon  pour réaliser vos tests ?

**Comment by Penfu** [comment]
Oui, le code productif ne contient maintenant plus de méthodes "exists". 
Les tests utilisent celles du package [VIR1-CORE](https://github.com/Thynkon/VIR1-CORE) afin de vérifier les dépendances à l'existence d'un objet AWS.

[Commit](https://github.com/yannickcpnv/VIR1-Deliver/commit/8f32a83c913503ab5b7bc4a9e84e77f4ccb0b4cb)
